addToLibrary({
  // CDC_Copy_Transmit is now provided in C (main_wrap.c) so the emulator can capture the
  // firmware's own $PMTXTS bytes; do NOT stub it here or the JS no-op would shadow the C def.
  doDateUpdate: function(){ return 0; },
  // f_open/f_read/f_lseek/f_close are now provided in C (main_wrap.c in-memory FATFS shim) so the
  // firmware's own loadRules() can parse the real /TZRULES.BIN. Keeping JS no-ops here would shadow
  // the C defs. f_stat stays stubbed (unused by the rules path).
  f_stat: function(){ return 0; },
  FATFS_remount: function(){ return 0; },
  firmwareCheckOnEject: function(){ return 0; },
  HAL_ADC_ConfigChannel: function(){ return 0; },
  HAL_ADC_Init: function(){ return 0; },
  HAL_ADC_PollForConversion: function(){ return 0; },
  HAL_ADC_Start: function(){ return 0; },
  HAL_ADCEx_Calibration_Start: function(){ return 0; },
  HAL_ADCEx_MultiModeConfigChannel: function(){ return 0; },
  HAL_CRC_Init: function(){ return 0; },
  HAL_DAC_ConfigChannel: function(){ return 0; },
  HAL_DAC_Init: function(){ return 0; },
  HAL_DAC_SetValue: function(){ return 0; },
  HAL_DAC_Start_DMA: function(){ return 0; },
  HAL_DMA_Abort: function(){ return 0; },
  HAL_DMA_Start: function(){ return 0; },
  HAL_GPIO_Init: function(){ return 0; },
  HAL_GPIO_WritePin: function(){ return 0; },
  HAL_Init: function(){ return 0; },
  HAL_NVIC_EnableIRQ: function(){ return 0; },
  HAL_NVIC_SetPriority: function(){ return 0; },
  HAL_PWR_EnableBkUpAccess: function(){ return 0; },
  HAL_PWREx_ControlVoltageScaling: function(){ return 0; },
  HAL_QSPI_Init: function(){ return 0; },
  HAL_RCC_ClockConfig: function(){ return 0; },
  HAL_RCC_OscConfig: function(){ return 0; },
  HAL_RCCEx_EnableMSIPLLMode: function(){ return 0; },
  HAL_RCCEx_PeriphCLKConfig: function(){ return 0; },
  HAL_RTC_GetDate: function(){ return 0; },
  HAL_RTC_GetTime: function(){ return 0; },
  HAL_RTC_Init: function(){ return 0; },
  HAL_TIM_Base_Init: function(){ return 0; },
  HAL_TIM_Base_Start: function(){ return 0; },
  HAL_TIM_ConfigClockSource: function(){ return 0; },
  HAL_TIM_MspPostInit: function(){ return 0; },
  HAL_TIM_OC_ConfigChannel: function(){ return 0; },
  HAL_TIM_OC_Init: function(){ return 0; },
  HAL_TIM_PWM_ConfigChannel: function(){ return 0; },
  HAL_TIM_PWM_Init: function(){ return 0; },
  HAL_TIM_PWM_Start: function(){ return 0; },
  HAL_TIMEx_MasterConfigSynchronization: function(){ return 0; },
  HAL_UART_AbortTransmit: function(){ return 0; },
  HAL_UART_Init: function(){ return 0; },
  HAL_UART_Receive_DMA: function(){ return 0; },
  HAL_UART_Transmit: function(){ return 0; },
  HAL_UART_Transmit_DMA: function(){ return 0; },
  MX_FATFS_Init: function(){ return 0; },
  MX_USB_DEVICE_Init: function(){ return 0; },
  MX_USB_Stop: function(){ return 0; },
});
